---
title: "Bolivia"
output: html_document
---

```{r warning = FALSE, include=FALSE}
#LIBRARY####
library(dygraphs)
library(tidyverse)
library(zoo)
library(rio)
library(magrittr)
library(janitor)
library(anytime)
library(knitr)
library(shiny)
library(plotly)
library(bookdown)
library(rmarkdown)
library(htmltools)
library(xaringanExtra)
library(tibbletime)
library(unikn)
library(scales)
library(ggnewscale)
library(patchwork)
library(kableExtra)
library(formattable)

knitr::opts_chunk$set(echo = TRUE, error = TRUE)

#FUNCIONES PLOTLY####
fun_excel <-function(file, range, sheet, col_names, from, to, by, each) {
  
  data <- 
    rio::import(
      file, 
      setclass = "tbl_df",
      sheet=sheet,
      range = range,
      col_names = col_names,
      .name_repair = "unique_quiet") %!>% 
    remove_empty(c("rows", "cols")) %!>%
    replace(is.na(.), 0)
  data %<>%
    pivot_longer(!...1) %<>%
    pivot_wider(names_from = "...1",
                values_from = "value") %<>%
    dplyr::select(-name)
  
  fecha <- fun_fecha(from,to,by,each)
  data <- cbind(fecha, data) 
  data <- as_tibble(data)
  
}
fun_fecha <-function(from, to, by, each) {
  rep(seq(anydate(from),
          anydate(to),
          by = by), each = each)
}
pal <- function(num) {
  usecol(c("#ff0000","#00ff00","#ffff00"),
         n = num)
}
pal_plotly <- function(num) {
  usecol(c("#ff0000","#00ff00","#0000ff","#ffff00"),
         n = num)
}
mi_paleta <- function(num) {
  usecol(c("#ff0000","#00ff00","#0000ff","#ffff00"),
         n = num)
}


plotly_bs <-  function(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs) {
  
  conjunto_datos_plotly <- conjunto_datos_bs %>%
    pivot_longer(!fecha, names_to = "variables", values_to = "valores")
  
  
  plot_ly(data = conjunto_datos_plotly, x = ~fecha, y = ~valores,
          color = ~variables, type = "scatter", mode = "lines", colors = mi_paleta_plotly) %>% 
    config(scrollZoom = FALSE, responsive = TRUE, displaylogo = FALSE,
           toImageButtonOptions = list(format= 'png', # one of png, svg, jpeg, webp
                                       filename= 'custom_image',
                                       height=  500,
                                       width= 700,
                                       scale= 1 )) %>% 
    layout(
      margin = list(l = 20, r = 20, b = 20, t = 40),
      paper_bgcolor = '#1d1d1d',
      plot_bgcolor = '#1d1d1d',
      xaxis = list( 
        zerolinewidth = F, 
        zerolinecolor = 'transparent',
        showgrid = F,
        title = list(text = " "), 
        tickfont = list(color = '#e3e3e3', family = "Constantia", size = 13),
        showline =TRUE,  
        linecolor = F,
        ticks = 'outside',
        hoverformat = "%b %Y"
      ), 
      yaxis = list( 
        zerolinewidth = 1,
        zerolinecolor = 'transparent',
        showgrid = F,
        title = list(text = " "), 
        tickformat = ",d",
        tickfont = list(color = '#e3e3e3', family = "Constantia", size = 13),
        showline = T,  
        linecolor = F, 
        ticks = 'outside'  
      ), 
      title = list(text = titulo_plotly_bs, x = 0.9, font = list(color = '#e3e3e3', family = "Constantia", size=15)), 
      legend = list(font = list(color = '#e3e3e3',size = 12, family = "Constantia"), orientation="h", traceorder= "normal"),  
      annotations = list(
        list(
          x = -0,  
          y = 1.07,  
          xref = "paper",
          yref = "paper",
          text = "bernalmauricio.com", 
          showarrow = FALSE,
          font = list(color = "#e3e3e3", family = "Arial")
        )
      )
    ) %>%
    plotly::style(hoverlabel = list(namelength = -1, font = list(family = "Constantia")))
}

plotly_usd <-  function(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd) {
  
  conjunto_datos_plotly <- conjunto_datos_usd %>%
    pivot_longer(!fecha, names_to = "variables", values_to = "valores")
  
  plot_ly(data = conjunto_datos_plotly, x = ~fecha, y = ~valores,
          color = ~variables, type = "scatter", mode = "lines", colors = mi_paleta_plotly) %>% 
    config(scrollZoom = FALSE, responsive = TRUE, displaylogo = FALSE,
           toImageButtonOptions = list(format= 'png', # one of png, svg, jpeg, webp
                                       filename= 'custom_image',
                                       height=  500,
                                       width= 700,
                                       scale= 1 )) %>% 
    layout(
      margin = list(l = 20, r = 20, b = 20, t = 40),
      paper_bgcolor = '#1d1d1d',
      plot_bgcolor = '#1d1d1d',
      xaxis = list( 
        zerolinewidth = F, 
        zerolinecolor = 'transparent',
        showgrid = F,
        title = list(text = " "), 
        tickfont = list(color = '#e3e3e3', family = "Constantia", size = 13),
        showline =TRUE,  
        linecolor = F,
        ticks = 'outside',
        hoverformat = "%b %Y"   
      ), 
      yaxis = list( 
        zerolinewidth = 1, 
        zerolinecolor = 'transparent',
        showgrid = F,
        title = list(text = " "), 
        tickformat = ",d",
        tickfont = list(color = '#e3e3e3', family = "Constantia", size = 13),
        showline = T,  
        linecolor = F, 
        ticks = 'outside'  
      ), 
      title = list(text = titulo_plotly_usd, x = 0.9, font = list(color = '#e3e3e3', family = "Constantia", size=15)), 
      legend = list(font = list(color = '#e3e3e3',size = 12, family = "Constantia"), orientation="h", traceorder= "normal"),  
      annotations = list(
        list(
          x = -0,  
          y = 1.07,  
          xref = "paper",
          yref = "paper",
          text = "bernalmauricio.com", 
          showarrow = FALSE,
          font = list(color = "#e3e3e3", family = "Arial")
        )
      )
    ) %>%
    plotly::style(hoverlabel = list(namelength = -1, font = list(family = "Constantia")))
  
}

html_table_width <- function(kable_output, width){
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub("<table>", paste0("<table>\n", width_html), kable_output)
}
dygraph_nominal_simple <- function(data, titulo, subtitulo, mi_paleta) {
  dygraph(data, main=paste(titulo, "<br>", subtitulo)) %>%
    dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE) %>%
    dyOptions(
      stackedGraph = FALSE,
      axisLineColor = "#6b7785",
      colors = mi_paleta) %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis(
      "y",
      drawGrid = FALSE,
      valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
      axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
    ) %>%
    dyCrosshair(direction = "vertical") %>%
    dyRangeSelector(height = 30) %>%
    dyHighlight(
      highlightCircleSize = 4,
      highlightSeriesBackgroundAlpha = 1
    )
}
dygraph_nominal_stacked <- function(data, titulo, subtitulo, mi_paleta) {
  dygraph(data, main=paste(titulo, "<br>", subtitulo)) %>%
    dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE) %>%
    dyOptions(
      stackedGraph = TRUE,
      axisLineColor = "#6b7785",
      colors = mi_paleta) %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis(
      "y",
      drawGrid = FALSE,
      valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
      axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
    ) %>%
    dyCrosshair(direction = "vertical") %>%
    dyRangeSelector(height = 30) %>%
    dyHighlight(
      highlightCircleSize = 4,
      highlightSeriesBackgroundAlpha = 1
    )
}
mi_paleta <- pal_plotly(10)
#BALANCE ACTIVO BCB####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/1.monetario/03a.activos_bcb.xlsx"

#IMPORTAR DATOS DE EXCEL
range <- "B6:Q305"
sheet <- "MENSUAL"
col_names <- FALSE
#FORMATO FECHA
from <- "01Jan1998"
to <- "01Dec2022"
by <- "month"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    sheet = sheet,
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)
colnames(data) <- c(
  "Reservas Internacionales Brutas",
  "Oro",
  "Divisas",
  "Otros Activos",
  "Aportes a Organismos Internacionales",
  "Otros Activos Externos de Mediano y Largo Plazo",
  "Crédito al Sector Público",
  "Al Gobierno Central",
  "A la Seguridad Social",
  "A Locales y Regionales",
  "A Empresas Públicas",
  "Crédito al Sector Financiero",
  "A Bancos Comerciales y en Liquidación",
  "A Bancos Especializados y Otras Entidades Financieras",
  "Otras Cuentas de Activo",
  "Total Activo"
)
fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
data <- as_tibble(data)

conjunto_datos_bs <- data %>%
  select(
    `fecha`,
    `Reservas Internacionales Brutas`,
    `Aportes a Organismos Internacionales`,
    `Otros Activos Externos de Mediano y Largo Plazo`,
    `Crédito al Sector Público`,
    `Crédito al Sector Financiero`,
    `Otras Cuentas de Activo`
  )%>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(
    `fecha`,
    `Reservas Internacionales Brutas`,
    `Aportes a Organismos Internacionales`,
    `Otros Activos Externos de Mediano y Largo Plazo`,
    `Crédito al Sector Público`,
    `Crédito al Sector Financiero`,
    `Otras Cuentas de Activo`
  )%>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))


titulo_plotly_bs <- "<b>Balance Activo del BCB</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Balance Activo del BCB</b><br>Millones $us"
mi_paleta_plotly <- pal_plotly(6)

#BALANCE ACTIVO DEL BCB LINE####

plotly_grafico_activo_lineal_bs <- plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_activo_lineal_usd <- plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)


#BALANCE ACTIVO DEL BCB STACK####

plotly_grafico_lineal_activo_y_stacked_bs <-  plotly_grafico_activo_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

plotly_grafico_lineal_activo_y_stacked_usd <-  plotly_grafico_activo_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

#BALANCE PASIVO BCB####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/1.monetario/03p.pasivos_bcb.xlsx"
#IMPORTAR DATOS DE EXCEL
range <- "B29:AE317"
sheet <- "Mensual"
col_names <- FALSE
#FORMATO FECHA
from <- "01Dec1998"
to <- "01Dec2022"
by <- "month"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    sheet = sheet,
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

colnames(data) <- c(
  
  "Emisión Monetaria",
  
  "Depósitos Bancarios",
  "Bancos Comerciales",
  "Bancos Especializados y Otras Entidades Financieras",
  
  "Obligaciones Externas de Corto Plazo",
  "Giros sobre el FMI",
  "Con Bancos y Otros Organismos",
  
  "Depósito de Organismos Internacionales",
  
  "Obligaciones Externas a Mediano y Largo Plazo",
  
  "Otras Cuentas Pasivo",
  
  "Certificado de Devolución de Depósito",
  "En Moneda Extranjera",
  "En Moneda Nacional con Mantenimiento de Valor",
  
  "Patrimonio Neto",
  
  "Depósitos del Sector Público",
  
  "Del Gobierno Central (GC)",
  "Del GC en Moneda Nacional",
  "Del GC en Unidad de Fomento de Valor",
  "Del GC en Moneda Extranjera",
  "Del GC en Moneda Nacional con Mantenimiento de Valor",
  
  "De la Seguridad Social (SS)",
  "De la SS en Moneda Nacional",
  "De la SS en Moneda Nacional con Mantenimiento de Valor",
  
  "De Gobiernos Locales y Regionales (GLyR)",
  "De GLyR en Moneda Nacional",
  "De GLyR en Moneda Extranjera",
  
  "De Empresas Públicas (EP)",
  "De EP en Moneda Nacional",
  "De EP en Moneda Extranjera",
  
  "Total Pasivo"
)

fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
data <- as_tibble(data)

conjunto_datos_bs <- data %>%
  select(`fecha`,
          `Emisión Monetaria`,
         `Depósitos Bancarios`,
         
         
         `Obligaciones Externas a Mediano y Largo Plazo`,
         `Otras Cuentas Pasivo`,
         
         `Patrimonio Neto`,
         `Depósitos del Sector Público`) %>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(`fecha`,
         `Emisión Monetaria`,
         `Depósitos Bancarios`,
         
         
         `Obligaciones Externas a Mediano y Largo Plazo`,
         `Otras Cuentas Pasivo`,
         
         `Patrimonio Neto`,
         `Depósitos del Sector Público`) %>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))

titulo_plotly_bs <- "<b>Balance Pasivo del BCB</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Balance Pasivo del BCB</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(6)


#BALANCE PASIVO DEL BCB LINE####

plotly_grafico_pasivo_lineal_bs <- plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_pasivo_lineal_usd <- plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)


#BALANCE PASIVO DEL BCB STACK####


plotly_grafico_lineal_pasivo_y_stacked_bs <-  plotly_grafico_pasivo_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_lineal_pasivo_y_stacked_usd <-  plotly_grafico_pasivo_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


#RESERVAS INTERNACIONALES####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/2.externo/29.reservas_internacionales_bcb.xlsx"

#IMPORTAR DATOS DE EXCEL
range <- "D120:G316"
sheet <- "Hoja1"
col_names <- FALSE
#FORMATO FECHA
from <- "01Dec2007"
to <- "01Apr2024"
by <- "month"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    sheet = sheet,
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

colnames(data) <- c(
  "Oro",
  "Divisas",
  "DEG",
  "Tramo de Reservas del FMI"
)

fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
conjunto_datos <- as_tibble(data)

conjunto_datos_bs <- conjunto_datos %>%
  mutate(across(where(is.numeric), ~  . * 6.86))

conjunto_datos_usd <- conjunto_datos

titulo_plotly_bs <- "<b>Reservas Internacionales del BCB</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Reservas Internacionales del BCB</b><br>Millones $us"

mi_paleta_plotly <- pal(4)

plotly_grafico_reservas_lineal_bs <- plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)

plotly_grafico_reservas_lineal_usd <- plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_lineal_reservas_y_stacked_bs <-  plotly_grafico_reservas_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_lineal_reservas_y_stacked_usd <-  plotly_grafico_reservas_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


#ORIGEN BASE MONETARIA####
#IMPORTAR DATOS DE EXCEL
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/1.monetario/01.base_monetaria.xlsx"
range <- "D24:S313"
col_names <- FALSE
#FORMATO FECHA
from <- "01Dec1998"
to <- "01Jan2023"
by <- "month"
each <- 1


data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

colnames(data) <- c(

  "Reservas Internacionales Netas",
  "Reservas Internacionales Brutas",
  "Obligaciones Externas a Corto Plazo",
  "Crédito Neto al Sector Público",
  "Crédito a Bancos",
  "BCL",
  "BE Y OEF",
  "Títulos Regulación Monetaria",
  "SRD",
  "Otras Cuentas Netas",
  "Base Monetaria",
  "Billetes y Monedas en poder del Público",
  "Reservas Bancarias en Moneda Nacional",
  "Reservas Bancarias en UFV",
  "Reservas Bancarias en Moneda Extranjera",
  "Total Reservas Bancarias"
  )

fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
data <- as_tibble(data)

conjunto_datos_bs <- data %>%
  select(fecha, 
         `Reservas Internacionales Netas`,
         `Crédito Neto al Sector Público`,
         `Crédito a Bancos`,
         `Títulos Regulación Monetaria`,
         `Otras Cuentas Netas`)%>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `Reservas Internacionales Netas`,
         `Crédito Neto al Sector Público`,
         `Crédito a Bancos`,
         `Títulos Regulación Monetaria`,
         `Otras Cuentas Netas`)%>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))

titulo_plotly_bs <- "<b>Origen Base Monetaria</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Origen Base Monetaria</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)


plotly_grafico_base_origen_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_base_origen_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_base_origen_lineal_y_stacked_bs <-  plotly_grafico_base_origen_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_base_origen_lineal_y_stacked_usd <-  plotly_grafico_base_origen_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)



#DESTINO BASE MONETARIA####

conjunto_datos_bs <- data %>%
  select(fecha, 
         `Billetes y Monedas en poder del Público`,
         `Reservas Bancarias en Moneda Nacional`,
         `Reservas Bancarias en UFV`,
         `Reservas Bancarias en Moneda Extranjera`)%>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `Billetes y Monedas en poder del Público`,
         `Reservas Bancarias en Moneda Nacional`,
         `Reservas Bancarias en UFV`,
         `Reservas Bancarias en Moneda Extranjera`)%>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))

titulo_plotly_bs <- "<b>Destino Base Monetaria</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Destino Base Monetaria</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)


plotly_grafico_base_destino_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_base_destino_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_base_destino_lineal_y_stacked_bs <-  plotly_grafico_base_destino_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_base_destino_lineal_y_stacked_usd <-  plotly_grafico_base_destino_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

#BALANZA CAMBIARIA INGRESO ANUAL####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/2.externo/33.balanza_cambiaria.xlsx"
#IMPORTAR DATOS DE EXCEL
range <- "A9:O84"
sheet <- "hoja_anual"
col_names <- FALSE
#FORMATO FECHA
from <- "01Dec2010"
to <- "01Dec2023"
by <- "year"
each <- 1

data <- fun_excel(file,range,sheet,col_names,from,to,by,each)
colnames(data)

conjunto_datos_bs <- data %>%
  select(fecha, 
         `I.A. Por Exportaciones`,
         `I.B. Renta`,
         `I.D. Bancos - Cheques`,
         `I.E. Desembolso Deuda Externa`,
         `I.J. Otros`)%>%
  mutate(across(where(is.numeric), ~  . *6.86 ))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `I.A. Por Exportaciones`,
         `I.B. Renta`,
         `I.D. Bancos - Cheques`,
         `I.E. Desembolso Deuda Externa`,
         `I.J. Otros`)

titulo_plotly_bs <- "<b>Balanza Cambiaria (Ingreso Divisas)</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Balanza Cambiaria (Ingreso Divisas)</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)


plotly_grafico_ingreso_cambiaria_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)

plotly_grafico_ingreso_cambiaria_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)


plotly_grafico_ingreso_cambiaria_lineal_y_stacked_bs <-  plotly_grafico_ingreso_cambiaria_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "bar", mode = "lines"), 
                      list(visible = c(FALSE, TRUE), barmode = "stack")),
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

plotly_grafico_ingreso_cambiaria_lineal_y_stacked_usd <-  plotly_grafico_ingreso_cambiaria_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "bar", mode = "lines"), 
                      list(visible = c(FALSE, TRUE), barmode = "stack")), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

conjunto_datos_bs <- data %>%
  select(fecha, 
         `II.A. Por Importación`,
         `II.B. Servicio Deuda Externa`,
         `II.C Sector Privado-Bancos`,
         `II.G Otros`,
         `II.H YPFB Costos Recuperables y Retribuciones a Empresas`)%>%
  mutate(across(where(is.numeric), ~  . *6.86 ))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `II.A. Por Importación`,
         `II.B. Servicio Deuda Externa`,
         `II.C Sector Privado-Bancos`,
         `II.G Otros`,
         `II.H YPFB Costos Recuperables y Retribuciones a Empresas`)

titulo_plotly_bs <- "<b>Balanza Cambiaria (Egreso Divisas)</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Balanza Cambiaria (Egreso Divisas)</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)

plotly_grafico_egreso_cambiaria_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)

plotly_grafico_egreso_cambiaria_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)


plotly_grafico_egreso_cambiaria_lineal_y_stacked_bs <-  plotly_grafico_egreso_cambiaria_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "bar", mode = "lines"), 
                      list(visible = c(FALSE, TRUE), barmode = "stack")),
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_egreso_cambiaria_lineal_y_stacked_usd <-  plotly_grafico_egreso_cambiaria_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "bar", mode = "lines"), 
                      list(visible = c(FALSE, TRUE), barmode = "stack")), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

#FINANCIAMIENTO DEL BCB AL SECTOR PUBLICO####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/1.monetario/06.financiamiento_bcb_sector_publico.xlsx"
range <- "B6:P314"
sheet <- "Hoja1"
col_names <- FALSE
#FORMATO FECHA
from <- "01Jan1998"
to <- "01Sep2023"
by <- "month"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    range = range,
    sheet = sheet,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

colnames(data) <- c(
  
  "Crédito Bruto a Gobierno Central",
  "Depósitos de Gobierno Central",
  "Crédito Neto a Gobierno Central",
  
  "Crédito Bruto a la Seguridad Social",
  "Depósitos de Seguridad Social",
  "Crédito Neto a Seguridad Social",
  
  "Crédito Bruto a Gobiernos Locales y Regionales",
  "Depósitos de Gobiernos Locales y Regionales",
  "Crédito Neto a Gobiernos Locales y Regionales",
  
  "Crédito Bruto a Empresas Públicas",
  "Depósitos de Empresas Públicas",
  "Crédito Neto a Empresas Públicas",
  
  "Crédito Bruto Total",
  "Depósitos Totales",
  "Crédito Neto Total"
)

fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
data <- as_tibble(data)

conjunto_datos_bs <- data %>%
  select(fecha, 
         `Crédito Bruto a Gobierno Central`,
         `Crédito Bruto a Empresas Públicas`)%>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `Crédito Bruto a Gobierno Central`,
         `Crédito Bruto a Empresas Públicas`)%>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))

titulo_plotly_bs <- "<b>Financiamiento del BCB al Sector Público</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Financiamiento del BCB al Sector Público</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)


plotly_grafico_credito_sector_publico_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_credito_sector_publico_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_credito_sector_publico_lineal_y_stacked_bs <-  plotly_grafico_credito_sector_publico_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

plotly_grafico_credito_sector_publico_lineal_y_stacked_usd <-  plotly_grafico_credito_sector_publico_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

#DEPOSITOS SECTOR PUBLICO EN BCB
conjunto_datos_bs <- data %>%
  select(fecha, 
         `Depósitos de Gobierno Central`,
         `Depósitos de Seguridad Social`,
         `Depósitos de Gobiernos Locales y Regionales`,
         `Depósitos de Empresas Públicas`)%>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `Depósitos de Gobierno Central`,
         `Depósitos de Seguridad Social`,
         `Depósitos de Gobiernos Locales y Regionales`,
         `Depósitos de Empresas Públicas`)%>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))

titulo_plotly_bs <- "<b>Depósitos del Sector Público en el BCB</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Depósitos del Sector Público en el BCB</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)


plotly_grafico_depositos_sector_publico_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_depositos_sector_publico_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_depositos_sector_publico_lineal_y_stacked_bs <-  plotly_grafico_depositos_sector_publico_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_depositos_sector_publico_lineal_y_stacked_usd <-  plotly_grafico_depositos_sector_publico_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

#CREDITO AL SECTOR PRIVADO####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/1.monetario/12.credito_sector_privado.xlsx"
sheet <- "Hoja1"
range <- "B61:F279"
col_names <- FALSE
#FORMATO FECHA
from <- "01Jan2006"
to <- "01Mar2024"
by <- "month"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    range = range,
    sheet = sheet,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

colnames(data) <- c(
  
  "La Paz",
  "Santa Cruz",
  "Cochabamba",
  "Resto del País",
  "Total"
)

fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
data <- as_tibble(data)

conjunto_datos_bs <- data %>%
  select(fecha, 
         `La Paz`,
         `Santa Cruz`,
         `Cochabamba`,
         `Resto del País`)%>%
  mutate(across(where(is.numeric), ~  . / 1000))

conjunto_datos_usd <- data %>%
  select(fecha, 
         `La Paz`,
         `Santa Cruz`,
         `Cochabamba`,
         `Resto del País`)%>%
  mutate(across(where(is.numeric), ~  . / 1000/6.86))

titulo_plotly_bs <- "<b>Crédito al Sector Privado (Departamentos)</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Crédito al Sector Privado (Departamentos)</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(4)

plotly_grafico_credito_sector_privado_depto_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_credito_sector_privado_depto_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_credito_sector_privado_depto_lineal_y_stacked_bs <-  plotly_grafico_credito_sector_privado_depto_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_credito_sector_privado_depto_lineal_y_stacked_usd <-  plotly_grafico_credito_sector_privado_depto_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)

file <- "C:/Users/Mauro/Desktop/bases_de_datos/bolivia/banco_central/4.mensual/1.monetario/18A.titulos_tgn_bcb.xlsx"
sheet <- "Hoja2"
range <- "B325:V376"
col_names <- FALSE
#FORMATO FECHA
from <- "01Dec2019"
to <- "01Mar2024"
by <- "month"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    range = range,
    sheet = sheet,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

colnames(data) <- c(
  
  "Letras MN",
  "Letras UFV",
  "Letras ME",
  "Letras",
  
  "Bonos MN",
  "Bonos UFV",
  "Bonos ME",
  "Bonos",
  
  "BCB Directo MN",
  "BCB Directo UFV",
  "BCB Directo ME",
  "BCB Directo",
  
  "CDDS",
  "Bonos BCB (Fianza)",
  "CDS ME y MVDOL",
  
  "RAL MN",
  "RAL UFV",
  "Fondo Ral",
  
  "CDS AFP (MN)",
  "Reservas Complementarias",
  "Deuda Interna del BCB"
)

fecha <- fun_fecha(from,to,by,each)
data <- cbind(fecha, data) 
data <- as_tibble(data)

conjunto_datos_bs <- data %>%
  select(fecha, 
         `Letras`,
         `Bonos`,
         `BCB Directo`,
         `Fondo Ral`,
         `CDS AFP (MN)`)

conjunto_datos_usd <- data %>%
  select(fecha, 
         `Letras`,
         `Bonos`,
         `BCB Directo`,
         `Fondo Ral`,
         `CDS AFP (MN)`) %>% 
  mutate(across(where(is.numeric), ~  . /6.86))

titulo_plotly_bs <- "<b>Deuda Interna del BCB con Sector Privado</b><br>Millones Bs"
titulo_plotly_usd <- "<b>Deuda Interna del BCB con Sector Privado</b><br>Millones $us"

mi_paleta_plotly <- pal_plotly(5)

plotly_grafico_deuda_bcb_privados_lineal_bs <-  plotly_bs(conjunto_datos_bs, mi_paleta_plotly, titulo_plotly_bs)
plotly_grafico_deuda_bcb_privados_lineal_usd <-  plotly_usd(conjunto_datos_usd, mi_paleta_plotly, titulo_plotly_usd)

plotly_grafico_deuda_bcb_privados_lineal_y_stacked_bs <-  plotly_grafico_deuda_bcb_privados_lineal_bs %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)


plotly_grafico_deuda_bcb_privados_lineal_y_stacked_usd <-  plotly_grafico_deuda_bcb_privados_lineal_usd %>% layout(
  updatemenus = list(
    list(
      x = 0.20, 
      y = 1.20,
      buttons = list(
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = FALSE), 
                      list(visible = c(TRUE, FALSE))), 
          label = 'Sin Apilar', 
          method = 'update'
        ),
        list(
          args = list(list(type = "scatter", mode = "lines", stackgroup = 'one'), 
                      list(visible = c(FALSE, TRUE))), 
          label = 'Apilado', 
          method = 'update'
        )
      )
    )
  )
)







```

### Banco Central de Bolivia (BCB)
<!-- Barra de navegación horizontal -->
<ul class="nav nav-tabs" id="nav-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="balance-tab" data-toggle="tab" href="#balance" role="tab" aria-controls="balance" aria-selected="true">Balance del BCB</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" id="balanzacamb-tab" data-toggle="tab" href="#balanzacamb" role="tab" aria-controls="balanzacamb" aria-selected="false">Balanza Cambiaria</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" id="basemon-tab" data-toggle="tab" href="#basemon" role="tab" aria-controls="basemon" aria-selected="false">Base Monetaria</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" id="credprivdepto-tab" data-toggle="tab" href="#credprivdepto" role="tab" aria-controls="credprivdepto" aria-selected="false">Crédito al Sector Privado (Departamentos)</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" id="deudaint-tab" data-toggle="tab" href="#deudaint" role="tab" aria-controls="deudaint" aria-selected="false">Deuda Interna del BCB con el Sector Privado</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" id="finbcb-tab" data-toggle="tab" href="#finbcb" role="tab" aria-controls="finbcb" aria-selected="false">Financiamiento del BCB al Sector Público</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" id="rin-tab" data-toggle="tab" href="#rin" role="tab" aria-controls="rin" aria-selected="false">Reservas Internacionales</a>
  </li>
  
</ul>

<!-- Contenido de las pestañas -->
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade active show" id="balance" role="tabpanel" aria-labelledby="balance-tab">
```{r bcb-activo, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_lineal_activo_y_stacked_bs
    plotly_grafico_lineal_pasivo_y_stacked_bs
    plotly_grafico_lineal_activo_y_stacked_usd
    plotly_grafico_lineal_pasivo_y_stacked_usd
```
  </div>
  
  <div class="tab-pane fade active" id="balanzacamb" role="tabpanel" aria-labelledby="balanzacamb-tab">
```{r bcb-base-balanzacamb, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_ingreso_cambiaria_lineal_y_stacked_bs
    plotly_grafico_egreso_cambiaria_lineal_y_stacked_bs
    plotly_grafico_ingreso_cambiaria_lineal_y_stacked_usd
    plotly_grafico_egreso_cambiaria_lineal_y_stacked_usd
``` 
  </div>

  <div class="tab-pane fade active" id="basemon" role="tabpanel" aria-labelledby="basemon-tab">
```{r bcb-base-monetaria, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_base_origen_lineal_y_stacked_bs
    plotly_grafico_base_destino_lineal_y_stacked_bs
    plotly_grafico_base_origen_lineal_y_stacked_usd
    plotly_grafico_base_destino_lineal_y_stacked_usd
``` 
  </div>

  <div class="tab-pane fade active" id="credprivdepto" role="tabpanel" aria-labelledby="credprivdepto-tab">
```{r bcb-cred-privado-depto, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_credito_sector_privado_depto_lineal_y_stacked_bs
    plotly_grafico_credito_sector_privado_depto_lineal_y_stacked_usd
``` 
  </div>

  <div class="tab-pane fade active" id="deudaint" role="tabpanel" aria-labelledby="deudaint-tab">
```{r bcb-cred-sector-privado, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_deuda_bcb_privados_lineal_y_stacked_bs
    plotly_grafico_deuda_bcb_privados_lineal_y_stacked_usd
``` 
  </div>

  <div class="tab-pane fade active" id="finbcb" role="tabpanel" aria-labelledby="finbcb-tab">
```{r bcb-fin, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_credito_sector_publico_lineal_y_stacked_bs
    plotly_grafico_depositos_sector_publico_lineal_y_stacked_bs
    plotly_grafico_credito_sector_publico_lineal_y_stacked_usd
    plotly_grafico_depositos_sector_publico_lineal_y_stacked_usd
``` 
  </div>

  <div class="tab-pane fade active" id="rin" role="tabpanel" aria-labelledby="rin-tab">
```{r bcb-rin, echo=FALSE, warning=FALSE, out.width=500}
    plotly_grafico_lineal_reservas_y_stacked_bs
    plotly_grafico_lineal_reservas_y_stacked_usd
``` 
  </div>
</div>