---
title: "Argentina"
output: html_document
---

```{r warning = FALSE, include=FALSE}
#LIBRARY####
library(dygraphs) 
library(tidyverse)
library(zoo)
library(rio)
library(tidyverse)
library(magrittr)
library(janitor)
library(anytime) 
library(knitr)
library(details)
library(DT)
library(shiny)
library(plotly)
library(bookdown)
library(rmarkdown)
library(htmltools)
library(xaringanExtra)
library(tibbletime)
library(unikn)
library(scales)
library(ggnewscale)
library(patchwork)
library(kableExtra)
library(formattable)

knitr::opts_chunk$set(echo = TRUE, error = TRUE)

#LABURO GGPLOT WRAP####
fun_excel <-function(file, range, sheet, col_names, from, to, by, each) {
  
  data <- 
    rio::import(
      file, 
      setclass = "tbl_df",
      sheet=sheet,
      range = range,
      col_names = col_names,
      .name_repair = "unique_quiet") %!>% 
    remove_empty(c("rows", "cols")) %!>%
    replace(is.na(.), 0)
  data %<>%
    pivot_longer(!...1) %<>%
    pivot_wider(names_from = "...1",
                values_from = "value") %<>%
    dplyr::select(-name)
  
  fecha <- fun_fecha(from,to,by,each)
  data <- cbind(fecha, data) 
  data <- as_tibble(data)
  
}
fun_fecha <-function(from, to, by, each) {
  rep(seq(anydate(from),
          anydate(to),
          by = by), each = each)
}
pal <- function(num) {
  usecol(c("#065a25", "#f2f419", "#f41919"),
         n = num)
}
html_table_width <- function(kable_output, width){
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub("<table>", paste0("<table>\n", width_html), kable_output)
}
dygraph_nominal_simple <- function(data, titulo, subtitulo, mi_paleta) {
  dygraph(data, main=paste(titulo, "<br>", subtitulo)) %>%
    dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE) %>%
    dyOptions(
      stackedGraph = FALSE,
      axisLineColor = "#6b7785",
      colors = mi_paleta) %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis(
      "y",
      drawGrid = FALSE,
      valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
      axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
    ) %>%
    dyCrosshair(direction = "vertical") %>%
    dyRangeSelector(height = 30) %>%
    dyHighlight(
      highlightCircleSize = 4,
      highlightSeriesBackgroundAlpha = 1
    )
}
dygraph_nominal_stacked <- function(data, titulo, subtitulo, mi_paleta) {
  dygraph(data, main=paste(titulo, "<br>", subtitulo)) %>%
    dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE) %>%
    dyOptions(
      stackedGraph = TRUE,
      axisLineColor = "#6b7785",
      colors = mi_paleta) %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis(
      "y",
      drawGrid = FALSE,
      valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
      axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
    ) %>%
    dyCrosshair(direction = "vertical") %>%
    dyRangeSelector(height = 30) %>%
    dyHighlight(
      highlightCircleSize = 4,
      highlightSeriesBackgroundAlpha = 1
    )
}

# Crear la paleta de colores
mi_paleta <- c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf")
pal <- function(num) {
  mi_paleta[seq_len(num)]
}


#BALANCE BCRA####
file <- "C:/Users/Mauro/Desktop/bases_de_datos/argentina/banco_central/3.mensual/2.dinero_credito/1.balances_consolidados/balbcrhis.xls"

#IMPORTAR DATOS DE EXCEL
range <- "B2:S27"
col_names <- TRUE
sheet <- "Hoja1"

#FORMATO FECHA
from <- "31Jan1998"
to <- "31Jan2022"
by <- "year"
each <- 1

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    range = range,
    sheet= sheet,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

Año <- fun_fecha(from,to,by,each)

data <- cbind(Año, data) 
data <- as_tibble(data)

hoja_excel <- as_tbl_time(data, index = Año) 
hoja_excel_ <- as_period(hoja_excel, period = "year", side = "end", include_endpoints = FALSE)

var_col <- colnames(data)[-c(1,10,19)]
names(hoja_excel_)
line_col <- 
  hoja_excel_ %!>%
  pivot_longer(
    cols = c(`Total Activo`, `Total Pasivo`),
    names_to = "var_line",
    values_to = "value_line"
  ) %!>%
  pivot_longer(cols = any_of(var_col),
               names_to = "var_col",
               values_to = "value_col") %!>%
  dplyr::filter(
    var_line %in% "Total Activo" &
      var_col %in% c("Reservas Internacionales",
                     "Títulos Públicos",
                     "Adelantos Transitorios al Gobierno",
                     "Creditos al Sistema Financiero",
                     "Aportes a Organismos Internacionales",
                     "Fondos Transferidos por el FMI",
                     "Derechos por Operaciones de Pase",
                     "Otros Activos") |
      var_line %in% "Total Pasivo" &
      var_col %in% c(
        "Base Monetaria",
        "Cuentas Corrientes en Otras Monedas",
        "Depósitos del Gobierno Nacional",
        "Títulos Emitidos por el BCRA",
        "Obligaciones por Operaciones de Pase",
        "Obligaciones con Organismos Internacionales",
        "Otros Pasivos",
        "Patrimonio Neto"
      )
  ) %!>%
  mutate(across(where(is.numeric),  ~ . / 1000000),
         across(where(is.character), as_factor),
         new_id=cur_group_id(),
         .by = var_line) %!>% 
  mutate(across(where(is.character), as_factor))

origen_g <- 
  line_col %!>% 
  dplyr::filter(
    new_id==1) 

destino_g <- 
  line_col %!>% 
  dplyr::filter(
    new_id==2) 

pal_fill <- 
  origen_g %!>%
  pull(var_col) %!>%
  unique() %!>% 
  length() %!>% 
  pal()

pal_col <- 
  origen_g %!>%
  pull(var_col) %!>%
  unique() %!>% 
  length() %!>% 
  pal()

p1  <- 
  ggplot(line_col,aes(Año,value_col))+
  
  geom_col(origen_g,mapping=aes(fill = var_col),
           color="#1d1d1d") +
  scale_fill_manual(values = pal_fill)+
  labs(fill="TOTAL ACTIVO")+
    
  new_scale_fill()+
    
  geom_col(destino_g,mapping=aes(fill = var_col),
           color="#1d1d1d")+ 
  scale_fill_manual(values = pal_fill)+
  labs(fill="TOTAL PASIVO")+  
  scale_y_continuous(labels = comma_format()) +
  
  facet_wrap(vars(var_line))+theme_wrap()

p2 <-    
  ggplot(destino_g,aes(Año,value_col))+
  geom_line(destino_g,mapping=aes(color = var_col),
            linewidth=1)+ 
  scale_color_manual(values = pal_col)+
  scale_y_continuous(labels = comma_format()) +
  guides(color = "none")+
  new_scale_color()+
  geom_line(origen_g,mapping=aes(color = var_col),
            linewidth=1)+
  scale_color_manual(values = pal_fill)+
  facet_wrap(vars(var_line))+
  guides(color = "none")+theme_wrap()

title <-"ACTIVO Y PASIVO DEL BCRA, 1998 - 2022"
subtitle <-"(miles de millones ARS)"
caption = "Fuente: Elaboración propia en base al BCRA\nBernal Mauricio / bernalmauricio.com"
anotattion <- plot_annotation(title = title,subtitle = subtitle,
                              caption = caption,theme = theme_annotations())

grafico_arg_1 <- (p1/p2)+plot_layout(guides = "collect")&anotattion

#KABLE###

#ACTIVO
#IMPORTAR DATOS DE EXCEL
range <- "B2:J27"
sheet <- "Hoja1"
col_names <- TRUE

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    sheet = sheet,
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

Año <- fun_fecha(from,to,by,each)
data <- cbind(Año, data) 
activo <- as_tibble(data)

#PASIVO
range <- "K2:S27"
sheet <- "Hoja1"
col_names <- TRUE

data <- 
  rio::import(
    file,
    setclass = "tbl_df",
    sheet = sheet,
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>%
  remove_empty(c("rows", "cols")) %!>%
  replace(is.na(.), 0)

Año <- fun_fecha(from,to,by,each)

data <- cbind(Año, data) 
pasivo <- as_tibble(data)

activo <- activo %!>% 
  mutate(across(where(is.numeric),  ~ . / 1000000))
pasivo <- pasivo %!>% 
  mutate(across(where(is.numeric),  ~ . / 1000000))

activo_ <- as_tbl_time(activo, index = Año) 
activo_1 <- as_period(activo_, period = "year", side = "end", include_endpoints = FALSE)

pasivo_ <- as_tbl_time(pasivo, index = Año) #FORMATO DATE FLEXIBLE
pasivo_1 <- as_period(pasivo_, period = "year", side = "end", include_endpoints = FALSE)

Año <- formattable(activo_1$Año, format = "%Y")

activo_1 <- activo_1[,-1]
pasivo_1 <- pasivo_1[,-1]

activo_arg_1 <- cbind(Año, activo_1) 
pasivo_arg_1 <- cbind(Año, pasivo_1) 


```

### Banco Central de la República Argentina (BCRA)
<!-- Barra de navegación horizontal -->
<ul class="nav nav-tabs" id="nav-tab" role="tablist">

  <li class="nav-item">
    <a class="nav-link active" id="balance-tab" data-toggle="tab" href="#balance" role="tab" aria-controls="balance" aria-selected="true">Balance del BCB</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" id="rin-tab" data-toggle="tab" href="#rin" role="tab" aria-controls="rin" aria-selected="false">Reservas Internacionales</a>
  </li>
  
  <li class="nav-item">
  <a class="nav-link" id="basemon-tab" data-toggle="tab" href="#basemon" role="tab" aria-controls="basemon" aria-selected="false">Base Monetaria</a>
  </li>
  
  <li class="nav-item">
  <a class="nav-link" id="balanzacamb-tab" data-toggle="tab" href="#balanzacamb" role="tab" aria-controls="balanzacamb" aria-selected="false">Balanza Cambiaria</a>
  </li>
  
</ul>

<!-- Contenido de las pestañas -->
<div class="tab-content" id="nav-tabContent">
  
  <div class="tab-pane fade active show" id="balance" role="tabpanel" aria-labelledby="balance-tab">
```{r bcb-activo, echo=FALSE, warning=FALSE, out.width=500}
dygraph_bcb_activo_simple
dygraph_bcb_pasivo_simple
dygraph_bcb_activo_stacked
dygraph_bcb_pasivo_stacked
```
  </div>
  
  <div class="tab-pane fade active" id="rin" role="tabpanel" aria-labelledby="rin-tab">
```{r bcb-rin, echo=FALSE, warning=FALSE, out.width=500}
dygraph_bcb_rin_simple
dygraph_bcb_rin_stacked
``` 
  </div>
  
  <div class="tab-pane fade active" id="basemon" role="tabpanel" aria-labelledby="basemon-tab">
```{r bcb-base-monetaria, echo=FALSE, warning=FALSE, out.width=500}
dygraph_origen_base_simple
dygraph_destino_base_simple
dygraph_origen_base_stacked
dygraph_destino_base_stacked
``` 
  </div>
  
  <div class="tab-pane fade active" id="balanzacamb" role="tabpanel" aria-labelledby="balanzacamb-tab">
```{r bcb-base-balanzacamb, echo=FALSE, warning=FALSE, out.width=500}
dygraph_cambiaria_ingreso_simple
dygraph_cambiaria_egreso_simple
dygraph_cambiaria_ingreso_stacked
dygraph_cambiaria_egreso_stacked
dygraph_cambiaria_saldo_simple
dygraph_cambiaria_saldo_stacked
``` 
  </div>
  
</div>


