---
title: "Gráficos"
output: html_document
---

```{r warning = FALSE, include=FALSE, echo=FALSE}
#LIBRARY####
library(dygraphs) 
library(tidyverse)
library(zoo)
library(rio)
library(tidyverse)
library(magrittr)
library(janitor)
library(anytime)
library(knitr)
library(details)
library(DT)
library(shiny)
library(plotly)
library(bookdown)
library(rmarkdown)
library(htmltools)
library(xaringanExtra)
library(tibbletime)
library(unikn)
library(scales)
library(ggnewscale)
library(patchwork)
library(kableExtra)
library(formattable)

knitr::opts_chunk$set(echo = TRUE, error = TRUE)

#LABURO GGPLOT WRAP####
fun_excel <-function(file, range, sheet, col_names, from, to, by, each) {
  
  data <- 
    rio::import(
      file, 
      setclass = "tbl_df",
      sheet=sheet,
      range = range,
      col_names = col_names,
      .name_repair = "unique_quiet") %!>% 
    remove_empty(c("rows", "cols")) %!>%
    replace(is.na(.), 0)
  data %<>%
    pivot_longer(!...1) %<>%
    pivot_wider(names_from = "...1",
                values_from = "value") %<>%
    dplyr::select(-name)
  
  fecha <- fun_fecha(from,to,by,each)
  data <- cbind(fecha, data) 
  data <- as_tibble(data)
  
}
fun_fecha <-function(from, to, by, each) {
  rep(seq(anydate(from),
          anydate(to),
          by = by), each = each)
}
pal <- function(num) {
  usecol(c("#065a25", "#f2f419", "#f41919"),
         n = num)
}
html_table_width <- function(kable_output, width){
  width_html <- paste0(paste0('<col width="', width, '">'), collapse = "\n")
  sub("<table>", paste0("<table>\n", width_html), kable_output)
}
dygraph_nominal_simple <- function(data, titulo, subtitulo, mi_paleta) {
  dygraph(data, main=paste(titulo, "<br>", subtitulo)) %>%
    dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE) %>%
    dyOptions(
      stackedGraph = FALSE,
      axisLineColor = "#6b7785",
      colors = mi_paleta) %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis(
      "y",
      drawGrid = FALSE,
      valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
      axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
    ) %>%
    dyCrosshair(direction = "vertical") %>%
    dyRangeSelector(height = 30) %>%
    dyHighlight(
      highlightCircleSize = 4,
      highlightSeriesBackgroundAlpha = 1
    )
}
dygraph_nominal_stacked <- function(data, titulo, subtitulo, mi_paleta) {
  dygraph(data, main=paste(titulo, "<br>", subtitulo)) %>%
    dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE) %>%
    dyOptions(
      stackedGraph = TRUE,
      axisLineColor = "#6b7785",
      colors = mi_paleta) %>%
    dyAxis("x", drawGrid = FALSE) %>%
    dyAxis(
      "y",
      drawGrid = FALSE,
      valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
      axisLabelFormatter = 'function(d){return d.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
    ) %>%
    dyCrosshair(direction = "vertical") %>%
    dyRangeSelector(height = 30) %>%
    dyHighlight(
      highlightCircleSize = 4,
      highlightSeriesBackgroundAlpha = 1
    )
}

# Crear la paleta de colores
mi_paleta <- c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd", "#8c564b", "#e377c2", "#7f7f7f", "#bcbd22", "#17becf")
pal <- function(num) {
  mi_paleta[seq_len(num)]
}

#PBI Y POBLACION MUNDIAL DYGRAPHS####

file <- "C:/Users/mauro/Desktop/bases_de_datos/2.organismos_internacionales/ourworldindata/world-gdp-over-the-last-two-millennia.csv"

excel <- import(file)
gdp <- excel$`World GDP in 2011 Int.$ (OWID based on World Bank & Maddison (2017))`/1000000000000
excel <-excel[c(-1,-2,-4)]
excel <- cbind(excel, gdp)


pib_mundial <- dygraph(excel, main = "PIB Mundial de los Últimos dos Milenios") %!>% 
  dySeries("gdp", 
           label = "Producto Interno Bruto Mundial", color="green") %!>% 
  dyLegend(width = 300, show = "onmouseover") %!>% 
  dyOptions(stackedGraph = TRUE, axisLineColor = "#6b7785") %!>%
  dyAxis("x", drawGrid = FALSE) %>%
  dyAxis("y", drawGrid = FALSE,
         valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
         axisLabelFormatter = 'function(d){return "$" + d + "\ billones"}'
  ) %!>% 
  dyCrosshair(direction = NULL) %!>% 
  dyRangeSelector(height = 30) %!>% 
  dyHighlight(highlightCircleSize = 2,
              highlightSeriesBackgroundAlpha = 1)

file <- "C:/Users/mauro/Desktop/bases_de_datos/2.organismos_internacionales/ourworldindata/total-population-living-in-extreme-poverty-by-world-region.csv"

excel <- import(file)

gdp <- excel$`Number of people living in extreme poverty - by world region`/1000000
excel <-excel[c(-2,-4)]
excel <- cbind(excel, gdp)
excel <-
  excel %>%
  relocate(Year)%>%
  pivot_wider(names_from = Entity, values_from = gdp)%>%
  select(`Year`, 
         `East Asia and Pacific`,
         `Europe and Central Asia`,
         `High income countries`,
         `Latin America and the Caribbean`,
         `Middle East and North Africa`,
         `South Asia`,
         `Sub-Saharan Africa`) 

pobreza_mundial <- dygraph(excel, main = "Población total que vive en pobreza extrema por región del mundo (millones de habitantes)") %!>% 
  dySeries("High income countries", 
           label = "Paises de Altos Ingresos", color = "#6D3E91") %!>% 
  dySeries("Latin America and the Caribbean", 
           label = "América Latina y el Caribe",color = "#C05917") %!>% 
  dySeries("East Asia and Pacific", 
           label = "Asia Oriental y el Pacífico",color = "#58AC8C") %!>% 
  dySeries("South Asia", 
           label = "Asia del Sur",color = "#286BBB") %!>% 
  dySeries("Middle East and North Africa", 
           label = "Oriente Medio y África del Norte",color = "#883039") %!>% 
  dySeries("Europe and Central Asia", 
           label = "Europa y Asia Central",color = "#BC8E5A") %!>% 
  dySeries("Sub-Saharan Africa", 
           label = "Africa Sub-Sahariana",color = "#00295B") %!>% 
  dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE, labelsDiv = FALSE) %!>% 
  dyOptions(axisLineWidth = 1.5,stackedGraph = TRUE, fillGraph = TRUE, axisLineColor = "#6b7785") %!>%
  dyAxis("x", drawGrid = FALSE) %>%
  dyAxis("y", drawGrid = FALSE,
         valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
         axisLabelFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
  ) %!>% 
  dyCrosshair(direction = NULL) %!>% 
  dyRangeSelector(height = 30) %!>% 
  dyHighlight(highlightCircleSize = 2,
              highlightSeriesBackgroundAlpha = 1,
              hideOnMouseOut = TRUE) 

#ESPERANZA DE VIDA DYGRAPHS####
file <- "C:/Users/mauro/Desktop/bases_de_datos/2.organismos_internacionales/ourworldindata/excel2.xlsx"
range <- "A1:G83"
col_names <- TRUE

data<- 
  rio::import(
    file, 
    setclass = "tbl_df",
    range = range,
    col_names = col_names,
    .name_repair = "unique_quiet") %!>% 
  remove_empty(c("rows", "cols")) 


esperanza_vida <- dygraph(data, main = "Esperanza de Vida<br><small>1770-2021</small>") %!>% 
  dySeries("Oceania", 
           label = "Oceania", color = "#18470f") %!>% 
  dySeries("Europe", 
           label = "Europa",color = "#6d3e91") %!>% 
  dySeries("Americas", 
           label = "America",color = "#2c8465") %!>% 
  dySeries("Asia", 
           label = "Asia",color = "#be5915") %!>% 
  dySeries("World", 
           label = "Mundo",color = "#cf0a66") %!>% 
  dySeries("Africa", 
           label = "Africa",color = "#c15065") %!>% 
  dyLegend(width = 300, show = "onmouseover", labelsSeparateLines = TRUE, labelsDiv = FALSE, showZeroValues = FALSE) %!>% 
  dyOptions(axisLineWidth = 1.5,stackedGraph = FALSE, fillGraph = FALSE, axisLineColor = "#6b7785") %!>%
  dyAxis("x", drawGrid = FALSE) %>%
  dyAxis("y", drawGrid = FALSE,
         valueFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}',
         axisLabelFormatter = 'function(d){return Math.round(d).toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, ",");}'
  ) %!>% 
  dyCrosshair(direction = NULL) %!>% 
  dyRangeSelector(height = 30) %!>% 
  dyHighlight(highlightCircleSize = 2,
              highlightSeriesBackgroundAlpha = 1,
              hideOnMouseOut = TRUE) 

```



### Estadísticas Mundiales
<!-- Barra de navegación horizontal -->
<ul class="nav nav-tabs" id="nav-tab" role="tablist">

  <li class="nav-item">
    <a class="nav-link active" id="pibmundial-tab" data-toggle="tab" href="#pibmundial" role="tab" aria-controls="pibmundial" aria-selected="true">PIB Mundial</a>
  </li>
  
  <li class="nav-item">
    <a class="nav-link" id="pobrezamundial-tab" data-toggle="tab" href="#pobrezamundial" role="tab" aria-controls="pobrezamundial" aria-selected="false">Pobreza Mundial</a>
  </li>
  
  <li class="nav-item">
  <a class="nav-link" id="esperanzavidamundial-tab" data-toggle="tab" href="#esperanzavidamundial" role="tab" aria-controls="esperanzavidamundial" aria-selected="false">Esperanza de Vida Mundial</a>
  </li>
  
</ul>

<!-- Contenido de las pestañas -->
<div class="tab-content" id="nav-tabContent">

  <div class="tab-pane fade active show" id="pibmundial" role="tabpanel" aria-labelledby="pibmundial-tab">
```{r pibmundial, echo=FALSE, warning=FALSE, out.width=500}
htmltools::tags$div(
  pib_mundial,
  style = "margin-bottom: 40px; width: 480px;"
)

```
</div>

<div class="tab-pane fade active" id="pobrezamundial" role="tabpanel" aria-labelledby="pobrezamundial-tab">
```{r pobrezamundial, echo=FALSE, warning=FALSE, out.width=500}
htmltools::tags$div(
pobreza_mundial,
  style = "margin-bottom: 40px; width: 480px;"
)


``` 

</div>

<div class="tab-pane fade active" id="esperanzavidamundial" role="tabpanel" aria-labelledby="esperanzavidamundial-tab">
```{r esperanzavidamundial, echo=FALSE, warning=FALSE, out.width=500}
htmltools::tags$div(
  esperanza_vida,
  style = "margin-bottom: 40px; width: 480px;"
)


``` 
</div>
  
  
</div>
